"""CLI command registry."""

from assistant_t800.application.commands import Command
from assistant_t800.localization import Message
from assistant_t800.application.handlers import (
    add_contact,
    add_email,
    add_phone,
    add_tag,
    close_app,
    edit_note,
    get_contact,
    list_contacts,
    list_upcoming_birthdays,
    remove_address,
    remove_birthday,
    remove_contact,
    remove_email,
    remove_note,
    remove_phone,
    remove_tag,
    search_contacts,
    search_contacts_by_email,
    search_contacts_by_name,
    search_contacts_by_note,
    search_contacts_by_phone,
    search_contacts_by_tag,
    set_address,
    set_birthday,
    show_help,
)


def build_registry() -> dict[str, Command]:
    """Build command registry with aliases."""
    commands = (
        Command(
            name="help",
            handler=show_help,
            description=Message.HELP_DESCRIPTION,
            aliases=("?", "допомога", "рудз"),
        ),
        Command(
            name="exit",
            handler=close_app,
            description=Message.EXIT_DESCRIPTION,
            aliases=("quit", "q", "учше"),
        ),
        Command(
            name="add",
            handler=add_contact,
            description=Message.ADD_DESCRIPTION,
            usage="add <name> [phone] [email] [address] [birthday]",
            parse_args=False,
            aliases=("додати", "фвв"),
        ),
        Command(
            name="contacts",
            handler=list_contacts,
            description=Message.CONTACTS_DESCRIPTION,
            aliases=("all", "контакти", "сщтефсеі"),
        ),
        Command(
            name="get",
            handler=get_contact,
            description=Message.GET_DESCRIPTION,
            args=("name",),
            aliases=("надай", "пуе"),
        ),
        Command(
            name="search",
            handler=search_contacts,
            description=Message.SEARCH_DESCRIPTION,
            args=("query",),
            aliases=("шукай", "знайди", "іуфкср"),
        ),
        Command(
            name="search-name",
            handler=search_contacts_by_name,
            description=Message.SEARCH_NAME_DESCRIPTION,
            args=("query",),
            aliases=(
                "шукай ім'я",
                "знайди ім'я",
                "іуфкср-тфьу",
                "search name",
                "іуфкср тфьу",
            ),
        ),
        Command(
            name="search-phone",
            handler=search_contacts_by_phone,
            description=Message.SEARCH_PHONE_DESCRIPTION,
            args=("query",),
            aliases=(
                "шукай телефон",
                "знайди телефон",
                "іуфкср-зрщту",
                "search phone",
                "іуфкср зрщту",
            ),
        ),
        Command(
            name="search-email",
            handler=search_contacts_by_email,
            description=Message.SEARCH_EMAIL_DESCRIPTION,
            args=("query",),
            aliases=(
                "шукай ємейл",
                "знайди ємейл",
                "іуфкср-уьфшд",
                "search email",
                "іуфкср уьфшд",
            ),
        ),
        Command(
            name="search-note",
            handler=search_contacts_by_note,
            description=Message.SEARCH_NOTE_DESCRIPTION,
            args=("query",),
            aliases=(
                "шукай нотатку",
                "знайди нотатку",
                "іуфкср-тщеу",
                "search note",
                "іуфкср тщеу",
            ),
        ),
        Command(
            name="search-tag",
            handler=search_contacts_by_tag,
            description=Message.SEARCH_TAG_DESCRIPTION,
            args=("query",),
            aliases=(
                "шукай тег",
                "знайди тег",
                "іуфкср-ефп",
                "search tag",
                "іуфкср ефп",
            ),
        ),
        Command(
            name="birthdays",
            handler=list_upcoming_birthdays,
            description=Message.BIRTHDAYS_DESCRIPTION,
            usage="birthdays [days]",
            optional_args=("days",),
            aliases=("дні народження", "іменинники", "ишкервфні"),
        ),
        Command(
            name="set-address",
            handler=set_address,
            description=Message.SET_ADDRESS_DESCRIPTION,
            args=("name", "address"),
            aliases=(
                "додай адресу",
                "іуе-фввкуіі",
                "set address",
                "іуе фввкуіі",
            ),
        ),
        Command(
            name="set-birthday",
            handler=set_birthday,
            description=Message.SET_BIRTHDAY_DESCRIPTION,
            args=("name", "birthday"),
            aliases=(
                "додай день народження",
                "іуе-ишкервфн",
                "set birthday",
                "іуе ишкервфн",
            ),
        ),
        Command(
            name="add-phone",
            handler=add_phone,
            description=Message.ADD_PHONE_DESCRIPTION,
            usage="add-phone <name> <phone>",
            parse_args=False,
            aliases=(
                "додай телефон",
                "фвв-зрщту",
                "add phone",
                "фвв зрщту",
            ),
        ),
        Command(
            name="add-email",
            handler=add_email,
            description=Message.ADD_EMAIL_DESCRIPTION,
            usage="add-email <name> <email>",
            parse_args=False,
            aliases=(
                "додай ємейл",
                "фвв-уьфшд",
                "add email",
                "фвв уьфшд",
            ),
        ),
        Command(
            name="remove",
            handler=remove_contact,
            description=Message.REMOVE_DESCRIPTION,
            args=("name",),
            aliases=("видали", "куьщму", "delete", "вудуеу"),
        ),
        Command(
            name="remove-address",
            handler=remove_address,
            description=Message.REMOVE_ADDRESS_DESCRIPTION,
            args=("name",),
            aliases=(
                "видали адресу",
                "куьщму-фввкуіі",
                "remove address",
                "куьщму фввкуіі",
                "delete-address",
                "вудуеу-фввкуіі",
                "delete address",
                "вудуеу фввкуіі",
            ),
        ),
        Command(
            name="remove-birthday",
            handler=remove_birthday,
            description=Message.REMOVE_BIRTHDAY_DESCRIPTION,
            args=("name",),
            aliases=(
                "видали день народження",
                "куьщму-ишкервфн",
                "remove-birthday",
                "куьщму ишкервфн",
                "delete-birthday",
                "вудуеу-ишкервфн",
                "delete birthday",
                "вудуеу ишкервфн",
            ),
        ),
        Command(
            name="remove-phone",
            handler=remove_phone,
            description=Message.REMOVE_PHONE_DESCRIPTION,
            usage="remove-phone <name> [phone]",
            parse_args=False,
            aliases=(
                "видали телефон",
                "куьщму-зрщту",
                "remove phone",
                "куьщму зрщту",
                "delete-phone",
                "вудуеу-зрщту",
                "delete phone",
                "вудуеу зрщту",
            ),
        ),
        Command(
            name="remove-email",
            handler=remove_email,
            description=Message.REMOVE_EMAIL_DESCRIPTION,
            usage="remove-email <name> [email]",
            parse_args=False,
            aliases=(
                "видали ємейл",
                "куьщму-уьфшд",
                "remove email",
                "куьщму уьфшд",
                "delete-email",
                "вудуеу-уьфшд",
                "delete email",
                "вудуеу уьфшд",
            ),
        ),
        Command(
            name="edit-note",
            handler=edit_note,
            description=Message.EDIT_NOTE_DESCRIPTION,
            usage="edit-note <name> <note>",
            parse_args=False,
            aliases=(
                "увше-тщеу",
                "edit note",
                "увше тщеу",
                "додай нотатку",
                "редагуй нотатку",
                "зміни нотатку",
            ),
        ),
        Command(
            name="remove-note",
            handler=remove_note,
            description=Message.REMOVE_NOTE_DESCRIPTION,
            args=("name",),
            aliases=(
                "куьщму-тщеу",
                "remove note",
                "куьщму тщеу",
                "delete-note",
                "вудуеу-тщеу",
                "delete note",
                "вудуеу тщеу",
                "видали нотатку",
            ),
        ),
        Command(
            name="add-tag",
            handler=add_tag,
            description=Message.ADD_TAG_DESCRIPTION,
            usage="add-tag <name> <tag>",
            parse_args=False,
            aliases=(
                "фвв-ефп",
                "add tag",
                "фвв ефп",
                "create-tag",
                "скуфеу-ефп",
                "create tag",
                "скуфеу ефп",
                "додай тег",
                "створи тег",
            ),
        ),
        Command(
            name="remove-tag",
            handler=remove_tag,
            description=Message.REMOVE_TAG_DESCRIPTION,
            usage="remove-tag <name> <tag>",
            parse_args=False,
            aliases=(
                "куьщму-ефп",
                "remove tag",
                "куьщму ефп",
                "delete-tag",
                "вудуеу-ефп",
                "delete tag",
                "вудуеу ефп",
                "видали тег",
            ),
        ),
    )

    result: dict[str, Command] = {}

    for command in commands:
        result[command.name] = command

        for alias in command.aliases:
            result[alias] = command

    return result
